image: maven:3.3.9-jdk-8

cache:
  paths:
    - .m2/repository

stages:
  - test
  - report

test_job:
  stage: test
  allow_failure: true
  services:
    - name: registry.gitlab.com/kkol1/demo
      alias: grid
  script:
    - mvn clean test -Dselenide.remote=http://grid:4444/wd/hub
  artifacts:
    paths:
      - target/allure-results
    when: always

report_job:
  stage: report
  allow_failure: true
  script:
      - mvn allure:report
  artifacts:
    paths:
      - target/allure-results
      - target/allure-report


