image: maven:3.3.9-jdk-8

cache:
  paths:
    - .m2/repository

test_job:
  stage: test
  services:
    - name: registry.gitlab.com/kkol1/demo
      alias: grid
  script:
    - mvn clean test -Dselenide.remote=http://grid:4444/wd/hub
  artifacts:
    paths:
      - target/allure-results


